name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  Event:
    name: Run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print the details  
        run: |
          echo "Deploy to docker hub"
         
